import { Listing, Message } from './types';

export const INITIAL_LISTINGS: (Listing & { owner: 'user' | 'other'; isRecommended?: boolean })[] = [
  {
    id: 'rec-1',
    title: 'MacBook Pro M3 Max',
    price: 290000,
    category: 'Electronics',
    condition: 'New',
    location: 'Mumbai, MH',
    time: '2h ago',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAYvISTbXF26IwgyKsXxaWLSmXiwRa2xC_Q3PBU3BZHVSx8hwZ5SOrcsD_5y2sX0spmyoZGRX83Hpne3Zq4wA_JeFqP2aQgWG4uGjamddVx2R5PmPT1Gmth4E2QEpB_sTA4JFLmFCTq3zTTnX7yKibqeYCBqpj3j6b-itg-jWOd6z5C0zKkahh1E_QiY9L-SRY6onHb8DD0GHLYbcAuxgo618diDLC5B7c3I3pl9YarRfMnU4LmZpWjrg',
    views: '1.5k',
    isFavorite: false,
    description: '16-inch, 64GB RAM, 2TB SSD. Pristine condition with original box.',
    tags: ['New'],
    status: 'active',
    owner: 'other',
    isRecommended: true
  },
  {
    id: 'rec-2',
    title: 'Skyline Penthouse',
    price: 104000000,
    category: 'Property',
    condition: 'New',
    location: 'NYC',
    time: '1d ago',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDE9j0z5I1_1mXENSNGnbAjGgJai9sSAq9fdrA5EjWloNh0VJO4n-hIUl1x6qedcgHLzHhYQJpLuA1ymfqufCqyLjNBmmhgY9tFf899JWjgl90xujlBwzQ04_qdWP8pxN3CZBDQTG-jl3_JWjwF_WiOLVJTOlORoAzOpfAs6X7-6FLbT1ehD5u0LsECZ4NCRlmGatspmjXxoN9OSmOEtiMDpWn9quZUI9yjGdg_3lRgZi9GSkVU5e137Q',
    views: '4.2k',
    isFavorite: false,
    description: '3 Bedroom, 4 Bath luxury apartment with private rooftop terrace and skyline view.',
    tags: [],
    status: 'active',
    owner: 'other',
    isRecommended: true
  },
  {
    id: 'rec-3',
    title: 'Model S Plaid',
    price: 7400000,
    category: 'Vehicles',
    condition: 'Used',
    location: '2.4k mi',
    time: '3d ago',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAcjmsyp5mksR7fT7CJfuU9hxjkAuK7JcUBSY_EOouSo38i3D4YZcY8T6lNVK_bGAZkmyOYneljCPyvEdO8_Y2PMHzdVaCHBswiZ_wveIjk0eLY1L_DbjWhKA-tpbzcP3y9dr54WrK4TGVFL7CjXfGNMY7YPCFM7W0SpuqT2xSrg5xVjfwW1ygkPLpviQjRmGX093TQ6yWRG0hKoqeUc5QluvxPCQQj_piGlYyb6EEEVkQ-4_WD6_kHxg',
    views: '2.9k',
    isFavorite: false,
    description: '2023 Stealth Black. Only 2,400 miles. Full Self-Driving hardware included. Single owner.',
    tags: [],
    status: 'active',
    owner: 'other',
    isRecommended: true
  },
  {
    id: 'rec-4',
    title: 'Mechanical Masterpiece',
    price: 1030000,
    category: 'Electronics',
    condition: 'Vintage',
    location: 'Box/Papers',
    time: '5h ago',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBRNypi5Y69hwCXtSKj7eg52X9N7RFZoSRXnZMBD8larTK75WT2mnEFm0DdbOlUKJyEKWs9pRpKVWySuvdKtwaBNMyiPaGmmHbj-u5ow4VB-1D1Q8nbnFZTxa2DDEoDlX3JNf0UoDnn1XPNCtAGdruuaFo4sbDeLfLrxyIJ4KgwoEKBSxGV6Bt_y3Z-vBrTPAFLCK4ozNKRDxi86MNwAAW4nXbRroGcjJwwnwl-p5UPm4F9RSsrZdCWxw',
    views: '980',
    isFavorite: false,
    description: 'Swiss-made limited edition mechanical wristwatch. Titanium case with premium sapphire glass.',
    tags: [],
    status: 'active',
    owner: 'other',
    isRecommended: true
  },
  {
    id: 'rec-5',
    title: 'Fidelity H1 Wireless',
    price: 37500,
    category: 'Electronics',
    condition: 'Refurbished',
    location: 'Certified',
    time: '12h ago',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuB5HHXfrKQJnoSy616lLhpVj76z7x4sf-lbdPSIzhMJ7j7lCGjLGlbjFK6CwYVzmk44jrba_8kEhKPrpYoAEWE5uaQEbLVThBIizsSYgWAb74N4vhBMS3LCAJ0mExR9KS6a5lX8K71t-lP8P_3CD-ZeoAJpSa7d1hWHWlKN8ZmAZFaiw5tVL6pjBQoFaiHzlxqiXRzWwruvY9pgXOK3a5Wvn5O8Q2Z0qo4XFW0KY6ApyCujWu2BZHWmbg',
    views: '540',
    isFavorite: false,
    description: 'Active noise cancelling headphones with 40-hour battery life. Fully certified refurbished. Like new.',
    tags: [],
    status: 'active',
    owner: 'other',
    isRecommended: true
  },
  {
    id: 'rec-6',
    title: 'Designer Home Office',
    price: 230000,
    category: 'Property',
    condition: 'New',
    location: 'Delivery',
    time: '1d ago',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBQCASND_PEDBX45uotn2Wsj6Q7XQYWVlT_UgTbCWDO7NBNDJNH2bDIjDciIv-RvRETNLMsfsYlP5UW7Y8rOwvIxnNKQcWaOIkQHt-PEzKAZQsYLR1I_ljHcvG2jw7-B4yMkOo-QMOJUOaV8qCX0IqbNh_ZWr3LJ_v6IA-1OtuTNJM8iKArkyYwW28K8KxvxnIeNgQuqiWvNmcuNXiEj-wftEbyzHR9av8hPvPRHjC8vZQFmzAIRKq04w',
    views: '1.1k',
    isFavorite: false,
    description: 'Complete premium workstation setup including modern standing desk and elite ergonomic chair.',
    tags: [],
    status: 'active',
    owner: 'other',
    isRecommended: true
  },
  {
    id: 'rec-7',
    title: 'Azure Voyager 40',
    price: 26500000,
    category: 'Vehicles',
    condition: 'Used',
    location: 'Miami, FL',
    time: '1w ago',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDz6Z9cxL1rNCVNtHSSzKOuU7ain-g0kMwzjL6HgU1jMAyOmbwBxgTcYSubXNiWCGQEAt0cbzSVuQayluPkI6zVKAVx6FgroaIaaKR-c5ZfdEBoAeEWz4qA4kEMIvpFY7XroYnN1ks5SYtsGxsaklQsnV60L85Tl2RPIe6zLL8k44jttSdfd-aohfQtCt1LuiZAzHEFy7C5zeLNnk5uYtZAIbISe2Do9UnPLA-INlUl7rK_a5nDZxRCFQ',
    views: '6.8k',
    isFavorite: false,
    description: '40ft premium Motor Yacht, featuring 2 luxurious cabins, fully serviced in 2023.',
    tags: [],
    status: 'active',
    owner: 'other',
    isRecommended: true
  },
  {
    id: 'rec-8',
    title: 'Eames Lounge Chair',
    price: 515000,
    category: 'Property',
    condition: 'Vintage',
    location: 'Vintage',
    time: '2d ago',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDnI7zRUjlCWMJlfVSLg-NqQYMkfU3dTihjdaxfwhaVK5e9-8w4vvFJxUHFD6nwU2DYWYhkgmhU-mJWnk2u76jEmJ9JNscGAnDw1Ssdd9rpu3LcrilAbSWvRwLfEmSCXWlMxt-OPTuDu7qKqqatlIZuBJogt14zPyIQb9O-x9TAyaJha7FxomDIQvwJ4kSgclfzGnMJ671vFU6j-fLDjAeQ9FRDfFbiPem9LzHrpVN97HAH9atXgnPtPw',
    views: '1.9k',
    isFavorite: false,
    description: 'Original 1970s production lounge chair in premium leather and beautiful polished walnut.',
    tags: [],
    status: 'active',
    owner: 'other',
    isRecommended: true
  },

  // Search Results exclusives (items 9 to 14 in the mock list)
  {
    id: 'search-1',
    title: 'Premium Mechanical Keyboard',
    price: 20500,
    category: 'Electronics',
    condition: 'New',
    location: 'Bangalore, KA',
    time: '2 hours ago',
    image: 'https://images.unsplash.com/photo-1511467687858-23d96c32e4ae?auto=format&fit=crop&q=80&w=600',
    views: '230',
    isFavorite: false,
    description: 'A high-end mechanical keyboard with custom keycaps, premium tactile switches, and solid aluminum chassis.',
    tags: [],
    status: 'active',
    owner: 'other'
  },
  {
    id: 'search-2',
    title: 'Vintage Leica M6 Camera',
    price: 260000,
    category: 'Electronics',
    condition: 'Used',
    location: 'Mumbai, MH',
    time: '5 hours ago',
    image: 'https://images.unsplash.com/photo-1510127034890-ba27508e9f1c?auto=format&fit=crop&q=80&w=600',
    views: '410',
    isFavorite: false,
    description: 'A classic Leica rangefinder film camera sitting in perfect functional and physical condition. Clean viewport.',
    tags: [],
    status: 'active',
    owner: 'other'
  },
  {
    id: 'search-3',
    title: 'Mid-Century Modern Lounge',
    price: 74000,
    category: 'Property',
    condition: 'Used',
    location: 'Delhi, DL',
    time: '1 hour ago',
    image: 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?auto=format&fit=crop&q=80&w=600',
    views: '880',
    isFavorite: false,
    description: 'A gorgeous designer mid-century modern lounge chair, with high-quality mustard textile and oak wood legs.',
    tags: [],
    status: 'active',
    owner: 'other'
  },
  {
    id: 'search-4',
    title: 'Electric Urban Commuter Bike',
    price: 148000,
    category: 'Vehicles',
    condition: 'New',
    location: 'Hyderabad, TS',
    time: '12 hours ago',
    image: 'https://images.unsplash.com/photo-1532298229144-0ee0c9e9ad58?auto=format&fit=crop&q=80&w=600',
    views: '350',
    isFavorite: false,
    description: 'A sleek, matte black urban electric bicycle. Built-in lights, disc brakes, and long range battery.',
    tags: [],
    status: 'active',
    owner: 'other'
  },
  {
    id: 'search-5',
    title: 'Artisanal Ceramic Coffee Set',
    price: 9800,
    category: 'Property',
    condition: 'New',
    location: 'Chennai, TN',
    time: '24 hours ago',
    image: 'https://images.unsplash.com/photo-1544991583-5335694bf13c?auto=format&fit=crop&q=80&w=600',
    views: '110',
    isFavorite: false,
    description: 'Handcrafted minimalist ceramic pour-over coffee carafe and two matching double-walled cups.',
    tags: [],
    status: 'active',
    owner: 'other'
  },
  {
    id: 'search-6',
    title: 'Ultra-Thin Pro Tablet',
    price: 89900,
    category: 'Electronics',
    condition: 'New',
    location: 'Pune, MH',
    time: '3 hours ago',
    image: 'https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?auto=format&fit=crop&q=80&w=600',
    views: '670',
    isFavorite: false,
    description: 'A cutting-edge tablet featuring a vibrant 120Hz display, high performance processor, and active stylus support.',
    tags: [],
    status: 'active',
    owner: 'other'
  },
  {
    id: 'job-1',
    title: 'Senior Frontend Developer (React)',
    price: 180000,
    category: 'Jobs',
    condition: 'Active',
    location: 'Bangalore, KA (Hybrid)',
    time: '4 hours ago',
    image: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?auto=format&fit=crop&q=80&w=600',
    views: '1.2k',
    isFavorite: false,
    description: 'Join our premium engineering team building high-performance marketplace services. You will design, build, and scale interactive micro-frontend modules with modern React and Tailwind CSS.',
    tags: ['React', 'Full-time', 'Hybrid'],
    status: 'active',
    owner: 'other',
    companyName: 'Vibe Tech Labs',
    jobType: 'Full-time',
    jobRequirements: '3+ years React & TypeScript experience; Strong visual layout discipline; Prior marketplace experience is a plus.'
  },
  {
    id: 'job-2',
    title: 'UI/UX Product Designer',
    price: 125000,
    category: 'Jobs',
    condition: 'Active',
    location: 'Mumbai, MH (Remote)',
    time: '1 day ago',
    image: 'https://images.unsplash.com/photo-1561070791-26c113006238?auto=format&fit=crop&q=80&w=600',
    views: '840',
    isFavorite: false,
    description: 'We are seeking an exquisite Product Designer with an obsession for negative space, typography pairings, and micro-interactions. You will craft the user journeys and interface guidelines for our next-gen mobile application.',
    tags: ['Figma', 'Remote', 'Creative'],
    status: 'active',
    owner: 'other',
    companyName: 'Glacier Design Studio',
    jobType: 'Remote',
    jobRequirements: 'Stellar visual portfolio demonstrating UI layout & spacing craft; 2+ years of figma experience; comfortable working asynchronously.'
  },
  {
    id: 'job-3',
    title: 'Growth & Business Analyst',
    price: 72000,
    category: 'Jobs',
    condition: 'Active',
    location: 'Delhi, DL',
    time: '2 days ago',
    image: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&q=80&w=600',
    views: '450',
    isFavorite: false,
    description: 'Vendo is looking for a data-focused Growth Analyst to study user funnel behavior, dashboard retention trends, and help direct our merchant success strategies. Training on advanced analytics platforms provided.',
    tags: ['Data', 'Full-time', 'On-site'],
    status: 'active',
    owner: 'other',
    companyName: 'Vendo Analytics',
    jobType: 'Full-time',
    jobRequirements: 'Proficiency in Excel/Google Sheets & SQL; basic understanding of marketplace funnels; excellent communication.'
  },

  // User Dashboard Listings (exclusives)
  {
    id: 'user-1',
    title: 'Silver Ultrabook Pro M2',
    price: 1299,
    category: 'Electronics',
    condition: 'Active',
    location: 'San Francisco, CA',
    time: '2h ago',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCyFA0NXnC-vOPCyt7i6UMzW8sZcY9vuLfkC85Y8mdcyyYhzSWFsFREYmbuH9UnV9LJ24eblyrb9C4sdX2M14ZvEYrEvI8Q9xM_6d7wWuhRpH7hiWYqjGHhpx1WAIenEtegUu9UkdFBX8rLDapPo4aVpJz_V-PpOIE4y_XgVjfmWAZss6fJ_vpxSgIZDPcavAS-BMJlTRtAbkq9jeYaWQdzrHHEPla8bvBRHJiww77E1rcN_EUEUgWaCQ',
    views: '1.2k',
    isFavorite: false,
    description: 'High-performance silver laptop with M2 equivalent silicon, 16GB memory, and stunning Retina-grade display.',
    status: 'active',
    owner: 'user'
  },
  {
    id: 'user-2',
    title: 'Noise-Canceling Studio Headphones',
    price: 350,
    category: 'Electronics',
    condition: 'Pending',
    location: 'San Francisco, CA',
    time: '1d ago',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuChgNM1WgRdlunflisR6bsU3a46nqOp31TftKNTQ09uAFZ8aZr4SMzrTc2QEiKIxI_4JuMhAMtoRRebqAS2WbVuoATm77dq1b5ypJk5rWD5UYLYMYeKkXpXvdvP1-AjLehD78A7MXBNOoAonfYkwpUhTfif5hg3EpmGxwL6vzAhoX5Nyaptka8DdcHvGxoHw8RMo0S9VtqfIDWOuigrpP4AUw8sHrIpAst54OSTTF7MUkTF4QV4uz5ePQ',
    views: '840',
    isFavorite: false,
    description: 'Premium over-ear studio headphones with pristine active noise cancellation and soft memory foam pads.',
    status: 'pending',
    owner: 'user'
  },
  {
    id: 'user-3',
    title: 'Ergonomic Office Chair',
    price: 180,
    category: 'Property',
    condition: 'Used',
    location: 'San Francisco, CA',
    time: 'Completed',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAonqnTJCyIFZ5VPTsumi7VqijIzi1Cd2Bqpokha1xVmoFQduYE2H8Unqx1f50N-z517hPqZL6XU_ytmfOVDczpp7bX0xjAJVqgTjyAQp49MUhozD-VDpBp4iJtl6gdmNZwyfbSBZ70D4tgRNdKbCflxWzw7ob1XnQPWCQjtQdJrodsrniTp4tWkd3ZUFxrEbouFRnSGrCptRJyHd7tHUFtdbQvQGOo7YP18iwKFOM29ovyyfg3XY5kPA',
    views: 'Completed',
    isFavorite: false,
    description: 'Sturdy black ergonomic office chair with lumbar adjustment, gas-lift, and 3D armrests.',
    status: 'sold',
    owner: 'user'
  }
];

export const INITIAL_MESSAGES: Message[] = [
  {
    id: 'msg-1',
    sender: 'Elena Rodriguez',
    avatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAhnkMFOcxypd4KFnBgr2f2KBWpKb2Zs7LpV4fQCwZSG35b6svz94VtAQJfjTwrPc_YrcmwrnD695_FfGtEUOvHZhL6mb3GI4tRiFJIAhChBsbsWcUZ0PLcqw3j2he2y4rf1r_8icTlVvka_cl-biwhqtZ2ldb-QheHozMiBhJrgqz5pF7WbU7yzLrjtFQH5HLbWgFefhsvkDAlG2qXiZbXmWC3fqGPkrUiImTe4NfVfz6qGVXLoAsUiA',
    time: '2m ago',
    message: 'Is the Ultrabook still available? I can meet today.',
    unread: true,
    active: true
  },
  {
    id: 'msg-2',
    sender: 'Marcus T.',
    avatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuANmGnFGfZWpbemZVary05gYSOrRIMpVqCk58J4moPxosctv2OZIX-6ByhXag3zCK6h_8Ze8ehLQUvyZi_l252DQ2QltWNnCoM8KMy1qMDnUy2XyuxOJLvcQ2WZvxxaVnoXPgQfuqgMtqLZFcinodShUKD4cbNNjN_lauL78pFIH5yLtW48z6qdcu3pTyJ3sZhPTjtszviOf_SCA7zha6q6IagSJbdf9UWZkiR4Tz8vMad4hx-zG7QPqg',
    time: '45m ago',
    message: 'Great, thanks for the info! Let me think about it...',
    unread: false
  },
  {
    id: 'msg-3',
    sender: 'David Wilson',
    avatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAlTbfKlxAtr1xKzcEl7Io1JG9c3ONCTX9xPL9rvMremGZJIWUY3pzrXknwXqT4WhOlEHPQ5zS1LUjT7m-zr_mXNue8IHBebGYunQ-VVNxOjdBYkTPkZ0nScJRpG0DUR4366z1CBAKIMYgtUUHjJEB9xWrVq-ZyQ_MggLWf0NOy9wdvvD_XD10PbycpTS_P_wwHrueHwvLw2kEYRQk45e6YCIpJ0xDVEwUyMCgZsy_dS9AXriKrql-XNg',
    time: '2h ago',
    message: 'Would you accept ₹150 for the office chair?',
    unread: false
  }
];

export const PROFILE_IMAGE = 'https://lh3.googleusercontent.com/aida-public/AB6AXuD3wZFi05fnxt1VJDmk4BzJDkdziAuLOaIwTu6cIh89ekIQe6NTefYvMucZDBv02ZxlYU2L0CJ4gy9Ck-_-RpYnSm0XV77mQDQaZfSVEfeKYTGnzTFIdhqUfNn_3SZ1WxlfwCBEnjrvLg_j73e5jVf8Wy83yqJ56Ose3VSG8gEpq_ScQNTkpWIew_NBu8bN_4kEYVwNk_nFyU9zIc_mDfc4F4iKKsnxSWLN9YURfKNs4f3vFsc5_VmiFg';
export const ALT_PROFILE_IMAGE = 'https://lh3.googleusercontent.com/aida-public/AB6AXuCj8fps8xXUAP-gf8NlKJbIAymke-0BFVmtA4hg4YkrjvSKEpVlyivthUBjB-OIwBKmV2Peww9vbPKSVMijhHKCxNvPEYyE-OW4uciBnxOTsALIT2HeqMUk8VnHj7KPSzL4YNOp1Vu5fWDYxAkYSpv_4amoumJGwDvPPOPURhpfzNt5WHw1v5J_IJ4eBmbnYhhprjlnv2jT-YWHFhJk9Z76qSe6gy4ayqGb0VXT6QkLhCJYM_giBm7pTw';
